"""Catch accidental changes to the public HTTP API.

The OpenAPI spec is generated by FastAPI from the route signatures and
the Pydantic models behind ``api/models.py``. Any change to those (a new
route, a renamed field, a tightened type) shifts the spec — and we want
those shifts to be **intentional**, not silent.

When this test fails:

1. Run ``uv run python scripts/update_openapi_snapshot.py`` to regenerate.
2. Review ``git diff tests/api/openapi.snapshot.json`` carefully.
3. If the change is intentional, commit the new snapshot alongside.
4. If it's surprising, the API regressed — fix the production code first.
"""

import json
from pathlib import Path

from easyfold.main import app

SNAPSHOT_PATH = Path(__file__).parent / "openapi.snapshot.json"


def test_openapi_snapshot_matches() -> None:
    """If this fails, run ``scripts/update_openapi_snapshot.py`` and review
    the diff. Intentional API changes get a snapshot bump committed with
    the change; unexpected diffs mean something regressed.
    """
    expected = json.loads(SNAPSHOT_PATH.read_text())
    actual = app.openapi()
    assert actual == expected, (
        "OpenAPI schema changed — run "
        "`uv run python scripts/update_openapi_snapshot.py` and review the diff."
    )


def test_openapi_has_jobs_endpoints() -> None:
    """Smoke check that the spec actually surfaces the Jobs API. Cheap
    insurance against snapshot tests being silently subverted by a broken
    snapshot file (e.g. an empty paths dict).
    """
    spec = app.openapi()
    paths = spec["paths"]
    assert "/api/v1/jobs" in paths
    assert "post" in paths["/api/v1/jobs"]
    assert "/api/v1/jobs/{job_id}" in paths
    assert "get" in paths["/api/v1/jobs/{job_id}"]
